version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  pre_build:
    commands:
      - cd A7-sam-app-url-shortener 
      - cd tests/unit
      - pip install pytest
      - pytest test_app.py

  build:
    commands:
      - cd ../..  
      - sam build

  post_build:
    commands:
    
      - echo "Build output copied to S3 bucket"

artifacts:
  files:
    - '**/*'
  
  name: build-output
  artifact: s3://s-bucket-cicd1/build-output/




