version: 0.2
build:
    commands:
    # Clone the repository
      # - git clone --no-checkout https://github.com/ShuchithaA/antstack-assignment.git
        
        # Navigate to the repository directory
      - cd antstack-assignment
        
        # Enable sparse-checkout
      - git sparse-checkout init
        
        # Set the subdirectory you're interested in
      - git sparse-checkout set A7-sam-app-url-shortener
        
        # Now checkout the files
      - git checkout
      - pip install -r requirements.txt
      - pip install pytest
      - pytest
      - sam build
      - sam deploy --stack-name sam-app-url-shortener --region ap-south-1 --parameter-overrides S3BucketName=s-bucket-cicd1  --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM --resolve-s3
