AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-url-shortener
  Sample SAM Template for sam-app-url-shortener
Resources:
  MyS3Bucket:
       Type: AWS::S3::Bucket
       Properties:
         BucketName: s-bucket-cicd1
  APIurl:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
       openapi: 3.0.1
       info:
         title: My API
         version: '1.0'
       paths:
          /route1:
            parameters:
              - name: queryParam
                in: query
            get:
              responses:
                '200':
                  description: Successful response
                  content:
                    application/json:
                      example:
                        message: "Success"
          /route2:
            get:
              x-amazon-apigateway-integration:
                httpMethod: GET
                type: aws_proxy
                # Use Fn::Sub to dynamically generate the endpoint
                uri: 
                  Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApi}.Prod/GET/route2
  URLShortenerFunction:
      Type: AWS::Serverless::Function 
      Properties:
        Handler: app.lambda_handler
        Runtime: python3.11
        CodeUri: ./
        Environment:
          Variables:
            TABLE_NAME: !Ref URLShortenerTable
            REGION_NAME: ap-south-1
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref URLShortenerTable
          - S3CrudPolicy:
          BucketName: !Ref MyS3Bucket
      
  URLShortenerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: s_url_shortener2
      AttributeDefinitions:
        - AttributeName: ShortID
          AttributeType: S
        - AttributeName: OriginalURL
          AttributeType: S
      KeySchema:
        - AttributeName: ShortID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: OriginalURLIndex
          KeySchema:
            - AttributeName: OriginalURL
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          
Outputs:
  URLShortenerFunction:
    Description: "URL Shortener Lambda Function"
    Value:
      Fn::GetAtt:
        - URLShortenerFunction
        - Arn
  URLShortenerTable:
    Description: "URL Shortener DynamoDB Table"
    Value:
      Fn::GetAtt:
        - URLShortenerTable
        - Arn
  
  MyApiUrl:
    Description: "API Gateway URL"
    Value:
      Fn::Sub:
        - "https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com/Prod"
        - ApiId: !Ref APIurl
