AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-url-shortener
  Sample SAM Template for sam-app-url-shortener
Resources:
  MyS3Bucket:
       Type: AWS::S3::Bucket
       Properties:
         BucketName: s-bucket-cicd1
  UrlshortenerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  URLShortenerFunction:
      Type: AWS::Serverless::Function 
      Properties:
        Handler: app.lambda_handler
        Runtime: python3.11
        CodeUri: ./url-shortener
        # s3://my-bucket/my-function.zip
        Environment:
          Variables:
            TABLE_NAME: !Ref URLShortenerTable
            REGION_NAME: ap-south-1
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref URLShortenerTable
          - S3CrudPolicy:
              BucketName: !Ref MyS3Bucket
        Events:
          MyApiEvent:
            Type: Api
            Properties:
              RestApiId: !Ref UrlshortenerApi
              Path: /path
              Method: get
              RequestParameters:
               - method.request.querystring.url: 
                  Required: true
                  Caching: false
          MyProxyEvent:
            Type: Api
            Properties:
              RestApiId: !Ref UrlshortenerApi
              Path: /{proxy+}
              Method: get
      
  URLShortenerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: s_url_shortener2
      AttributeDefinitions:
        - AttributeName: ShortID
          AttributeType: S
        - AttributeName: OriginalURL
          AttributeType: S
      KeySchema:
        - AttributeName: ShortID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: OriginalURLIndex
          KeySchema:
            - AttributeName: OriginalURL
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          
Outputs:
  URLShortenerFunction:
    Description: "URL Shortener Lambda Function"
    Value:
      Fn::GetAtt:
        - URLShortenerFunction
        - Arn
  URLShortenerTable:
    Description: "URL Shortener DynamoDB Table"
    Value:
      Fn::GetAtt:
        - URLShortenerTable
        - Arn
  

